GET http://localhost:3000/users/69af7b123ea86c8d633158d5

###

GET http://localhost:3000/users/

###

POST http://localhost:3000/users
Content-Type: multipart/form-data; boundary=hr-boundary

--hr-boundary
Content-Disposition: form-data; name="name"

Bob
--hr-boundary
Content-Disposition: form-data; name="height"

180
--hr-boundary
Content-Disposition: form-data; name="weight"

150
--hr-boundary
Content-Disposition: form-data; name="phone"

5555554444
--hr-boundary
Content-Disposition: form-data; name="email"

bob@example.com
--hr-boundary
Content-Disposition: form-data; name="image"; filename="1584549321588.jpg"
Content-Type: image/jpeg

< FILE PATH HERE
--hr-boundary--

###

DELETE http://localhost:3000/users/69a4de3654e9739bf3c4d3ba

###

PATCH http://localhost:3000/users/69a3a06231f6c7d707d4f1fa
Content-Type: application/json

{
    "name": "Mike",
    "weight": "160",
    "email": "dunno@email"
}

